---

- name: Create open-cluster-management namespace
  kubernetes.core.k8s:
    state: present
    api_version: v1
    kind: Namespace
    name: open-cluster-management
    
- name: Create Operator Group for rhacm operator
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: open-cluster-management
        namespace: open-cluster-management
      spec: {}

- name: Create subscription for rhacm operator
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: advanced-cluster-management
        namespace: open-cluster-management
      spec:
        channel: release-2.6
        installPlanApproval: Automatic
        name: advanced-cluster-management
        source: redhat-operators
        sourceNamespace: openshift-marketplace
#       startingCSV: {{ rhacm_version }}





